# Generated by Django 5.0.2 on 2024-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saree',
            name='material',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='saree',
            name='sample_image',
            field=models.ImageField(upload_to='saree_images/'),
        ),
    ]
