# Generated by Django 5.0.1 on 2024-02-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor_record',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
