# Generated by Django 5.0.2 on 2024-02-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0002_alter_saree_material_alter_saree_sample_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saree',
            name='material',
            field=models.CharField(max_length=100),
        ),
    ]
