# Generated by Django 5.0.1 on 2024-02-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0003_rename_saree_date_price_sareedateprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorrecord',
            name='deadline_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='distributorrecord',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='distributorrecord',
            name='received_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='distributorrecord',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
