# Generated by Django 5.0.1 on 2024-02-24 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0004_alter_distributorrecord_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorrecord',
            name='deadline_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='distributorrecord',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='distributorrecord',
            name='received_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='distributorrecord',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
