# Generated by Django 5.0.2 on 2024-02-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0005_alter_distributorrecord_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saree',
            name='sample_image',
            field=models.ImageField(blank=True, upload_to='saree_images/'),
        ),
    ]
