# Generated by Django 5.0.1 on 2024-03-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0003_alter_saree_material'),
        ('wholesaler', '0006_alter_saree_sample_image'),
    ]

    operations = [
    ]
