# Generated by Django 5.0.2 on 2024-03-07 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0007_merge_20240307_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorrecord',
            name='deadline_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='distributorrecord',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='distributorrecord',
            name='return_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='saree',
            name='sample_image',
            field=models.ImageField(blank=True, upload_to='saree_images/'),
        ),
    ]
