# Generated by Django 5.0.1 on 2024-03-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0007_merge_20240309_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermerchent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Requested'), (1, 'Confirmed')], default=0),
        ),
        migrations.AlterField(
            model_name='saree',
            name='sample_image',
            field=models.ImageField(blank=True, upload_to='saree_images/'),
        ),
    ]
