# Generated by Django 5.0.1 on 2024-03-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0008_usermerchent_status_alter_saree_sample_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermerchent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Requested'), (1, 'Confirmed'), (2, 'Declined')], default=0),
        ),
    ]
