# Generated by Django 5.0.2 on 2024-03-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0008_alter_distributorrecord_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorrecord',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
