# Generated by Django 5.0.2 on 2024-03-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0009_alter_distributorrecord_return_date'),
        ('wholesaler', '0009_alter_usermerchent_status'),
    ]

    operations = [
    ]
