# Generated by Django 5.0.2 on 2024-03-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0010_merge_20240310_2001'),
        ('wholesaler', '0011_notifications'),
    ]

    operations = [
    ]
