# Generated by Django 5.0.2 on 2024-03-16 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0012_merge_0010_merge_20240310_2001_0011_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorrecord',
            name='deadline_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='distributorrecord',
            name='received_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='distributorrecord',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
