# Generated by Django 5.0.2 on 2024-03-24 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0013_alter_distributorrecord_deadline_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorrecord',
            name='commission',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
    ]
