# Generated by Django 5.0.2 on 2024-03-24 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0014_distributorrecord_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorrecord',
            name='return_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
