# Generated by Django 5.0.1 on 2024-03-28 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0015_alter_distributorrecord_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='who_add',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
